config/routes.rb
Rails.application.routes.draw do
  # 管理者用ルート
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show] do
      resources :photos, only: [:index, :show, :destroy], controller: 'photos'
    end
  end

  # ユーザー関連のルート
  scope module: :public do
    root to: 'homes#top'
      resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'confirm_withdraw', to: 'users#confirm_withdraw', as: 'confirm_withdraw'
      patch 'withdraw', to: 'users#withdraw', as: 'withdraw'
    end
    resources :goods, only: [:index, :create, :destroy]
    resources :photos do
      resources :comments, only: [:create, :destroy]
      member do
        post 'good', to: 'goods#create', as: 'good_photo'
        delete 'good', to: 'goods#destroy', as: 'nogood_photo'
      end
    end
  end
  resources :timelines, only: [:index]
  get '/search', to: 'searches#search', as: 'search'
  end

  # ユーザー用ルート
  devise_for :users, skip: [:passwords], path: '', path_names: { sign_in: 'login', sign_up: 'register' }, controllers: {
    registrations: "public/registrations",
      sessions: 'public/sessions'
  }
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # ゲストユーザーの場合は新しい User オブジェクトを作成

    can :read, Photo # 誰でも写真を閲覧できる

    if user.persisted?
      can :create, Photo # ログインユーザーは写真を投稿できる
      if user.admin?
        can :destroy, Photo # 管理者は全ての写真を削除できる
      else
        can :destroy, Photo, user_id: user.id # ログインユーザーは自分の写真を削除できる
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  has_many :goods, dependent: :destroy
  has_many :good_users, through: :goods, source: :user
  has_one_attached :image
  validates :image, presence: true
  validates :title, presence: true
  validates :caption, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/timeline.rb
class Timeline < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :goods
  has_many :good_photos, through: :goods, source: :photo
  has_many :comments
  has_many :photos
  attribute :deleted, :boolean, default: false
  # 追加：admin属性を持つユーザーを管理者として判断するメソッド
  def admin?
    self.admin
  end
  def goods?(photo)
    goods.exists?(photo_id: photo.id)
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  before_action :authenticate_admin! # ユーザーがログインしていることを確認
  load_and_authorize_resource :user
  load_and_authorize_resource :photo, through: :user # 認可を確認

  def index
    @photos = @user.photos.page(params[:page]).per(6) # 1ページあたり6件表示
  end

  def show
    # CanCanCanがすでに@photoを設定しているため、何もしない
  end

  def destroy
    if @photo.destroy
      redirect_to admin_user_photos_path(@user), notice: '写真が削除されました。'
    else
      flash.now[:danger] = '写真の削除に失敗しました。'
      render :show
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana])
  end

  def after_sign_in_path_for(resource)
    if resource.deleted?
      sign_out resource
      flash[:alert] = "このアカウントは削除されました"
      new_user_session_path
    else
      super
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if user_signed_in?
      # ログインしている場合の処理
      # タイムライン上の写真を取得するクエリを追加する
      @timeline_photos = Photo.order(created_at: :desc).limit(10)
    else
      # ログインしていない場合の処理
      # 代替のコンテンツを表示するか、何もしないか、必要に応じて実装
      # 以下は例ですが、適切なコンテンツに変更してください
      @alternative_content = "ログインしていません。ログインまたは新規登録をしてください。"
    end

    # 他の必要なロジックや変数の設定を行う

    # ビューに渡すデータを設定する
    # この行は必要に応じて変更してください
    @some_other_variable = "Some data"

    # ビューを描画する
    render "top"
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    # タイムラインに表示するコンテンツを取得するロジックを記述
    @timeline_photos = Photo.all.order(created_at: :desc)  # 例: 投稿を新しい順に取得

    respond_to do |format|
      format.html
      format.json { render json: @timeline_photos }  # タイムラインデータをJSON形式で提供する場合
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to users_path(current_user.id)
  end

  def confirm_withdraw
    @user = current_user
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/photos/index.html.erb
<h1 class="text-center my-4">投稿一覧</h1>

<div class="container">
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <%= link_to admin_user_photo_path(photo.user, photo) do %>
            <% if photo.image.attached? %>
              <%= image_tag photo.image.variant(resize:'400x400').processed, class: 'card-img-top' %>
            <% end %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= photo.title %></h5>
            <p class="card-text"><%= photo.caption %></p>
              <!-- いいねされている数 -->
              <p><%= photo.goods.count %> いいね</p>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/photos/show.html.erb
<div class="d-flex justify-content-center align-items-center">
  <!-- 投稿画像 -->
  <div class="p-2">
    <%= image_tag url_for(@photo.image.variant(resize:'500x500').processed), class: "img-fluid", size: "500x500" %>
  </div>

  <!-- タイトルと説明 -->
  <div class="p-2">
    <!-- タイトル -->
    <h2><%= @photo.title %></h2>

    <!-- 説明 -->
    <p><%= @photo.caption %></p>
  </div>
</div>

<div class="d-flex justify-content-start align-items-center ml-5" style="position: relative;">
  <div style="position: absolute; left: 50%; transform: translateX(20%); margin-top: 20px;">
    <!-- コメント数 -->
    <p class="mb-0 align-self-center" style="display: inline-block;"><strong>コメント数:</strong> <%= @photo.comments.count %></p>
    <!-- 写真を削除 -->
    <% if admin_signed_in? %>
      <%= link_to '写真を削除', admin_user_photo_path(@photo.user, @photo), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'text-danger' %>
    <% end %>
  </div>
</div>

<!-- コメント一覧 -->
<div style="margin-top: 50px; margin-left: 710px; max-height: 300px; overflow-y: scroll; direction: rtl;">
  <div id="comment" style="direction: ltr;">
    <% @photo.comments.each do |comment| %>
      <div style="display: flex; align-items: center;">
        <div>
          <strong><%= comment.user.name %>:</strong> <%= comment.caption %>
        </div>
        <div style="margin-left: 20px; min-width: 150px;">
          <small>投稿時間: <%= comment.created_at.strftime("%Y年%m月%d日 %H時%M分") %></small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/index.html.erb
<h1>投稿一覧</h1>

<% @photos.each do |photo| %>
  <div class="photo">
    <%= image_tag photo.image.url %>
    <h2><%= photo.title %></h2>
    <p><%= photo.caption %></p>
    
    <!-- いいねボタン -->
    <% if user_signed_in? %>
      <% if current_user.likes?(photo) %>
        <%= link_to 'いいねを取り消す', unlike_photo_path(photo), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'いいね', like_photo_path(photo), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% else %>
      <%= link_to 'ログインしていいね', new_user_session_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/photos/new.html.erb
<h1>新規投稿</h1>

<%= form_with model: @photo, url: photos_path do |f| %>
        <table>
          <tr>
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image %></th>
          </tr>
          <tr>
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :title, placeholder:"タイトル" %></td>
          </tr>
          <tr>
            <th><%= f.label :説明 %></th>
            <td><%= f.text_area :caption, class: "form_control",rows: 5, placeholder:"ここに説明文を記述します" %></td>
          </tr>
          <tr>
          <tr>
            <th><%= f.submit "新規登録", class: "btn btn-success" %></th>
          </tr>
        </table>
<% end %>

app/views/photos/show.html.erb
<!-- 投稿画像 -->
<%= image_tag @photo.image.url, class: "img-fluid" %>

<!-- いいねボタン -->
<% if user_signed_in? %>
  <%= link_to "いいね", good_photo_path(@photo), method: :post, remote: true, class: "btn btn-primary" %>
<% end %>

<!-- タイトル -->
<h2><%= @photo.title %></h2>

<!-- コメント一覧 -->
<% @photo.comments.each do |comment| %>
  <div>
    <strong><%= comment.user.email %>:</strong> <%= comment.caption %>
  </div>
<% end %>

<!-- コメント数 -->
<p><strong>コメント数:</strong> <%= @photo.comments.count %></p>

<!-- コメント投稿フォーム -->
<% if user_signed_in? %>
  <%= form_for [@photo, Comment.new], remote: true do |f| %>
    <%= f.text_area :caption, placeholder: "コメントを入力してください", class: "form-control" %>
    <%= f.submit "コメントする", class: "btn btn-success" %>
  <% end %>
<% end %>

<!-- 写真削除ボタン（投稿者のみ表示） -->
<% if user_signed_in? && @photo.user == current_user %>
  <%= link_to '写真を削除', @photo, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
<% end %>