config/routes.rb
Rails.application.routes.draw do
  # 管理者用ルート
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show] do
      resources :photos, only: [:index, :show, :destroy], controller: 'photos'
    end
  end

  # ユーザー関連のルート
  scope module: :public do
    root to: 'homes#top'
      resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'confirm_withdraw', to: 'users#confirm_withdraw', as: 'confirm_withdraw'
      patch 'withdraw', to: 'users#withdraw', as: 'withdraw'
    end
    resources :goods, only: [:index, :create, :destroy]
    resources :photos do
      resources :comments, only: [:create, :destroy]
      member do
        post 'good', to: 'goods#create', as: 'good_photo'
        delete 'good', to: 'goods#destroy', as: 'nogood_photo'
      end
    end
  end
  resources :timelines, only: [:index]
  get '/search', to: 'searches#search', as: 'search'
  end

  # ユーザー用ルート
  devise_for :users, skip: [:passwords], path: '', path_names: { sign_in: 'login', sign_up: 'register' }, controllers: {
    registrations: "public/registrations",
      sessions: 'public/sessions'
  }
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # ゲストユーザーの場合は新しい User オブジェクトを作成

    can :read, Photo # 誰でも写真を閲覧できる

    if user.persisted?
      can :create, Photo # ログインユーザーは写真を投稿できる
      if user.admin?
        can :destroy, Photo # 管理者は全ての写真を削除できる
      else
        can :destroy, Photo, user_id: user.id # ログインユーザーは自分の写真を削除できる
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos
  has_many :goods, dependent: :destroy
  has_many :good_users, through: :goods, source: :user
  has_one_attached :image
  validates :image, presence: true
  validates :title, presence: true
  validates :caption, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/timeline.rb
class Timeline < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :goods
  has_many :good_photos, through: :goods, source: :photo
  has_many :comments
  has_many :photos
  attribute :deleted, :boolean, default: false
  # 追加：admin属性を持つユーザーを管理者として判断するメソッド
  def admin?
    self.admin
  end
  def goods?(photo)
    goods.exists?(photo_id: photo.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    if user_signed_in?
      # ログインしている場合の処理
      # タイムライン上の写真を取得するクエリを追加する
      @timeline_photos = Photo.order(created_at: :desc).limit(10)
    else
      # ログインしていない場合の処理
      # 代替のコンテンツを表示するか、何もしないか、必要に応じて実装
      # 以下は例ですが、適切なコンテンツに変更してください
      @alternative_content = "ログインしていません。ログインまたは新規登録をしてください。"
    end

    # 他の必要なロジックや変数の設定を行う

    # ビューに渡すデータを設定する
    # この行は必要に応じて変更してください
    @some_other_variable = "Some data"

    # ビューを描画する
    render "top"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    user.update(user_params)
    redirect_to users_path(current_user.id)
  end

  def confirm_withdraw
    @user = current_user
  end

  def withdraw
    @user = User.find(current_user.id)
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ようこそ！OldShrineへ！</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/3fa250182e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
            <%= link_to "マイページ", user_path(current_user), class: 'nav-link text-dark' %>
            </li>
            <li>
            <%= link_to "新規投稿", new_user_photo_path(current_user), class: 'nav-link text-dark' %>
            </li>
            <li>
            <%= link_to "投稿一覧", user_photos_path(current_user), class: 'nav-link text-dark' %>
            </li>
            <li>
            <%= link_to "いいね一覧", user_goods_path(current_user), class: 'nav-link text-dark' %>
            </li>
            <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% elsif admin_signed_in? %>
            <li>
            <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark' %>
            </li>
            <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li>
            <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li>
            <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            <!-- 検索フォーム -->
            <li class="nav-item">
            <form class="form-inline" action="<%= search_path %>" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="検索" aria-label="検索" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
            </form>
            </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if user_signed_in? || admin_signed_in? %>
    <% end %>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>廃神社好きが集まるSNS</p>
            <%= image_tag('logo.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>